### ISSUE TITLE
No usbrply.py?

### ISSUE THREAD

**Issue by sannong** [JohnDMcMaster/usbrply#33] opened 2020-05-18 22:00 UTC
Hello, 

I just downloaded the code (commit 9bf1beafaff129fb0c9ad6ad3665de07ce8f9e73) and am attempting to get it setup in my environment. The readme indicates to run 'usbrply --device-hi -p my.pcapng >replay.py' but there is no usbrply executable or file to call in any directory? Similarly setup.py searches for usbrply.py but cannot find it. Is there some other build step needed not specified in the readme that needs to be performed prior to use?

Thank you

**Comment by JohnDMcMaster** [comment] 2020-05-19 01:05
Hi there! It looks like there was possibly a regression during a recent major refactor. set.up and/or the instructions probably need to be updated. I'll get back to you shortly

**Comment by JohnDMcMaster** [comment] 2020-05-19 02:16
Should be fixed in master (via https://github.com/JohnDMcMaster/usbrply/commit/cdea59e78becb6950f7e36ed32c2ae7057ba4822)

Please let me know if you have any more issues!

**Closed by JohnDMcMaster** 2020-05-19 02:16 UTC

**Comment by sannong** [comment] 2020-05-19 13:57
Thanks! Works now.
